### PR TITLE
initial travis-ci support

### PR DESCRIPTION
**Pull request by chipitsine**

### CODE REVIEW

**Comment by mattock** [comment]
Looks pretty good, and it [seems to work](https://travis-ci.org/chipitsine/openvpnserv2/builds/178999234) in your own fork. As discussed in pull request https://github.com/OpenVPN/openvpnserv2/pull/5 perhaps testing "Any CPU" would be enough? That said, I'm fine with building all the variants just in case.

Also, I know that the build scripts fail on more recent Mono versions, such as those included in Fedora 23+. I guess the "dist: trusty") masks that problem, as the most recent mono on that platform is pretty old. That is not related to this PR, though, but just something we should fix at some point.

**Comment by chipitsine** [comment]
I will provide complex patch, which removes x86, x64 from csproj, not only build.sh

Actually, I think app veyor would be enough, but I will have a look at fedora core 25

**Comment by mattock** [comment]
Ok, great! The problem is probably not Fedora-specific, but Fedora just happens to have very up-to-date Mono installed.

**Comment by mattock** [comment]
@chipitsine just noticed this when looking at openvpnserv2 PRs. Should we get this fixed and merged?

**Comment by chipitsine** [comment]
probably. I'll have a look today.

there's not much activity

**Comment by mattock** [comment]
Activity is indeed low. Then again, openvpnserv2 seems stable so there's little need to modify it. But eventually someone does and we benefit from having Travis integration.

**Comment by mattock** [comment]
@chipitsine ping :smile:

**Comment by chipitsine** [comment]
pong!

ok, will do today

**Pull request closed without merging**
