### PR TITLE
Autostart config dir

### PR DESCRIPTION
**Pull request by selvanair**
As discussed under openvpn-build PR 141.

See commit messages for details.

Tested on Windows 7

### CODE REVIEW

**Comment by mattock** [comment]
Looks good to me. Took me a while to understand what the code is doing, not looking at it or C# in some years. Interesting the "continue" actually means "break", i.e. start the next round in a loop.

**Comment by mattock** [comment]
Oh, and this of course won't affect any new installers as we fetch openvpnserv2.exe separately as a dependency.

**Comment by mattock** [comment]
I've built openvpnserv2.exe so far. The exe URL is defined in openvpn-build/windows-nsis/build-complete.vars.

**Comment by selvanair** [comment]
Yes, the yet non-existing link to the 1.4.0.0 service executable is included in my PR for openvpn-build. Once that is merged new installers will require the new service and start bundling it.

**Pull request merged**
