### PR TITLE
Exit event v2 (Using C# calls)

### PR DESCRIPTION
**Pull request by xkjyeah**

### CODE REVIEW

**Comment by mattock** [comment]
@selvanair : I'll run this PR through my testsuite.

**Comment by mattock** [comment]
Based on my testing this version of exit-event patch "seems to work". As we're pushing out OpenVPN 2.4_beta1 in a few hours, this won't make it into that release. However, 2.4_rc1 is not many weeks away, so the delay is not that bad. Also, this way we can subject this to more rigorous testing.

**Comment by selvanair** [comment]
My tests also show this works well. As it avoids native C calls (P/Invoke), this is a better approach too. That said, let's wait for more thorough testing by @mattock.

**Comment by mattock** [comment]
We did not receive any feedback from our users on openvpn-devel mailing list regarding this PR. I think we will have to merge this as-is and fix any issues that might arise later.

**Comment by selvanair** [comment]
This looks good to me, so ACK from me.

**Comment by mattock** [comment]
I think these two commits should be squashed before merge:
* Use an exit-event to stop openvpn instead of killing it
* Use C# built-in event signalling methods?

The "Set logfile to autoflush" commit should remain on its own (if possible).

Besides that I think we can merge this.

**Comment by selvanair** [comment]
I made a squashed branch here  -- log file autoflush made the first commit, the other two squashed with two signed-off authors. @xkjyeah if you are ok with this, please merge it to your local branch and force push.

**Comment by selvanair** [comment]
Sorry, forgot to add the link. Here goes again:

I made a squashed commit [here](https://github.com/selvanair/openvpnserv2/commit/5af338478caa8f5542a82b8fc42a8c58884806e7) in this [banch](https://github.com/selvanair/openvpnserv2/tree/exit-event-v2)
-- log file autoflush made the first commit, the other two squashed with two signed-off authors. @xkjyeah if you are ok with this, please merge it to your local branch and force push.

**Comment by mattock** [comment]
Selva did the squashing and issued a PR, which got merged. Closing this one.

**Pull request closed without merging**
