### PR TITLE
Exit the build early if there's an error

### PR DESCRIPTION
**Pull request by xkjyeah**
Improvement on the Linux build script (build.sh).

This terminates the build when an error occurs

### CODE REVIEW

**Comment by xkjyeah** [comment]
Oh right. I forgot about this possibility...

**Comment by chipitsine** [comment]
probably it makes more sense to build on travis-ci
as for building *.sln on Linux, it is "very well known", I'm afraid we do not need both build.sh and build.bat

**Comment by xkjyeah** [comment]
I'm not too familiar with the tools available on Linux, but the reason for
the script was to build for multiple platforms (x64, x86) (build, debug) at
one go. Is it possible to do that without a script?

**Comment by chipitsine** [comment]
c# is managed, I'm not sure why do we need x86, x64 builds.
I guess "Any CPU" should be enough

however,

https://travis-ci.org/chipitsine/openvpnserv2/builds/178999234

**Comment by xkjyeah** [comment]
Good point. It was because the service installer (installutil.exe) has two
versions, one for 32 Bit and one for 64 bit. But since we are no longer
using that to install the service the "Any CPU" build should suffice.

**Comment by mattock** [comment]
@xkjyeah : based on a _quick_ Internet search it is not possible to build multiple build configurations as a batch in Monodevelop. One can define multiple configurations, yes, but one has to flip a switch.

I think having separate build scripts makes sense anyways: if we did not have them, we would have to document how to build from the command-line, and that documentation would be at least as long as the script itself. Forcing people to search for build instructions on the Internet, or to use Monodevelop (or Visual Studio) is a bit too much imho.

As @chipitsine said, it probably makes sense to modify the script to build Release and Debug builds using the "Any CPU" option.

**Comment by flichtenheld** [comment]
Replaced by #15

**Pull request closed without merging**
